### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by megansegle** [cavpp/image_rename_and_convert#7]
hi henry,
i've been using the renaming/convert script with no issues. started again this morning with the state library whittier images and got this message:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/rename_files/gui.py", line 256, in _load_files_click
    self.load_files(source=self.lineEdit_source.text(), destination=self._destination, smart_sorting=smart)
  File "/usr/local/lib/python3.4/site-packages/rename_files/gui.py", line 573, in load_files
    self.update_tree()
  File "/usr/local/lib/python3.4/site-packages/rename_files/gui.py", line 477, in update_tree
    record = QTreeWidgetItem(self.tree_files, ["", "", str(queue.files[0]["id"]), project_id, simple])
IndexError: list index out of range

**Comment by henryborchers** [comment]
The problem was the files were using uppercase extensions. I fixed it so that this script doesn't care the case anymore the case.
